### ISSUE TITLE
2017.4 isue

### ISSUE THREAD

**Issue by riconstudio** [ShadesOfInsomnia/SpellSystem#14]
I use 2017.4.3f1 and get this error:

Assets/Invector-3rdPersonController/Add-ons/ShadesSpellSystem/Scripts/GenericRIGController.cs(1,16): error CS0234: The type or namespace name `EventSystem' does not exist in the namespace `Invector'. Are you missing an assembly reference?

I use Invector Melee 2.3.2

**Comment by insomniaunleashed** [comment]
hi mate

due to the latest invector changes i am depricating the generic rig, you will need to delete files
- GenericRIGController.cs
- GenericRIGRagdoll.cs

and in shadexComponents.cs comment out the reference to the above
//[MenuItem("Invector/Shades Spell System/Character Components/Generic RIG Controller")]
//static void MagicAIControllerMenu()
//{
// if (Selection.activeGameObject)
// Selection.activeGameObject.AddComponent<GenericRIGController>();
// else
// Debug.Log("No Active Selection");
//}


another break you will need to fix

in vHealthController.cs change

public OnReceiveDamage onReceiveDamage { get { return _onReceiveDamage; }protected set { _onReceiveDamage = value; } }

to

public OnReceiveDamage onReceiveDamage { get { return _onReceiveDamage; } set { _onReceiveDamage = value; } }

aka lose the protected keyword

invector have promised to lose the protected keyword in their next release
