### ISSUE TITLE
Controller Issues

### ISSUE THREAD

**Issue by CreativePlay** [ShadesOfInsomnia/SpellSystem#5]
Hello,

It seems with the new Unity update it is causing all the exit transitions to be removed. I think I corrected them all but I'm still receiving this error:

> Asset 'MagicMeleeCombatv2': Transition 'Fireball (2) Release -> INVALID' in state 'Fireball (2) Release' transitions to state '' which does not exist in controller.

Do you know what this means?

**Comment by insomniaunleashed** [comment]
this is actually one of the outstanding issues, it only effects charging spells, which work fine but we never got down to the actual solution to the warning, added to the github issue list so it does get resolved in due course. Note this is not due to the new unity version and was appearing in 2017.1 and 2017.2

**Comment by insomniaunleashed** [comment]
this was resolved awhile ago, via the new animator
